name: Test

on: push

jobs:
  test:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - uses: microsoft/setup-msbuild@v1.1
      - run: msbuild psyche.sln /t:restore /p:RestorePackagesConfig=true
      - run: msbuild psyche.sln /t:build
        env:
          CPPUTEST_HOME: cpputest-3.8
