name: Test

on: push

jobs:
  test:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - uses: microsoft/setup-msbuild@v1.1
      - name: Restore
        run: msbuild psyche.sln /t:restore /p:RestorePackagesConfig=true
      - name: Build
        run: msbuild psyche.sln /t:build
      - name: Run tests
        run: .\x64\Debug\UnitTest.exe
