name: Test

on: push

jobs:
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - uses: microsoft/setup-msbuild@v1.1
      - name: Restore
        run: msbuild psyche.sln /t:restore /p:RestorePackagesConfig=true
      - name: Build
        run: msbuild psyche.sln /t:build
      - name: Run tests
        run: .\x64\Debug\UnitTest.exe

  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - name: Install googletest
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          mkdir build
          cd build
          cmake ..
          make
          sudo make install
      - name: Build tests
        run: ninja
        working-directory: vm
      - name: Run tests
        run: ./build/test
        working-directory: vm

  macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - name: Install googletest
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          mkdir build
          cd build
          cmake ..
          make
          sudo make install
      - name: Build tests
        run: ninja
        working-directory: vm
      - name: Run tests
        run: ./build/test
        working-directory: vm
