name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.0
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git
            coq-released: https://coq.inria.fr/opam/released
      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest --instrument-with bisect_ppx --force
      - run: opam exec -- bisect-ppx-report send-to Codecov
